language: python
dist: xenial
sudo: false
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.5
    env: TOXENV=py35
  - python: 3.5-dev
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.6-dev
    env: TOXENV=py36
  - name: Python 3.7 on Xenial Linux
    python: 3.7
    env: TOXENV=py37
    dist: xenial
    sudo: true
  - python: 3.8
    env: TOXENV=py38
  - python: 3.9
    env: TOXENV=py39
  - python: 3.9-dev
    env: TOXENV=py39
  - python: pypy2.7-6.0
    env: TOXENV=py35
  - python: pypy3.6-7.3.1
    env: TOXENV=ALL
notifications:
  email:
    recipients:
    - jtonye@ymail.com
env:
  matrix:
  - DJANGO_SETTINGS_MODULE=django_extra_field_validation.settings
  global:
    secure: 1fKjh9h9jOorEabnmhKgvr1MTFcQTqvGoN9HNaQEewgoSF07Kyr5vt391BL7iP6bVQ/ntx8XU3KoB+voiXqP3PcKs0o8qKzglbRpWLTeJ+J9tpUDMpeIxIGH75/3taFEu565V3r65LwSpRK73v2L55Zwm2WEw5B4xA1Nm5O9P/ofXaP0lzCz2OBhI0UYxCtD+QkSwfI4DqUkWjLGcqVV8pRvdwYxs0oH8NfZaXDR/314TTu5Y39jJVXrtRRvg6sA2scMtLQ3INgWWgpfZCgMm28R5gEBL35Z+U1Yxx/o70xeDLgycyF5X/TDnNBP9t8gy7HLyBpJo8kvJQPT4sExWCetwEoi8RQBASX9SuLaDNpazdvQyuO/Mgw1oJGG1dXf0qsRk74VzmCGY+vzyVEW0+NpjiutxgKT+D6NVkBXJqgTNxXGLaZZbeUVPgeLur0YzfrXdI5lx7lm8vCjzPjKCQ7UUB8OJMiC2rWcLd9qvN8T90EcHBeW8CtN1BIvpDazGrxjHeGq2k4mB+vbsnxfiNlsu0Nn1yl/GJIIXxNGwRrd3MPoKUz4gpltRWlN8/a4tA9V9Ht4lQ/4OCGeoCBgcZZU9Va3pG+eE74jFMPSop6R4fwHxk38XuISq+C8jbJdQhr9cH9lWVAXApvHcyCazl0/q7bPqwYmpmtS8cTn6WU=
install:
- pip install -U pip tox
script:
- sqlite3 --version
- tox
